# Generated by Django 5.2 on 2025-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('quercus', 'Oak'), ('pinus', 'Pine')], max_length=10, verbose_name='Tree type'),
        ),
    ]
